import {
  Anchor,
  Aperture,
  ArrowDown,
  ArrowUp,
  Award,
  Beaker,
  Bell,
  BookMarked,
  BookOpen,
  Brain,
  Briefcase,
  Cake,
  Calendar,
  Camera,
  Check,
  CheckCheck,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  CloudFog,
  Cog,
  Coins,
  Compass,
  Contrast,
  CreditCard,
  Crown,
  Download,
  Ellipsis,
  ExternalLink,
  Eye,
  EyeOff,
  Feather,
  Flag,
  Flame,
  FlaskConical,
  FlaskRound,
  Gem,
  Ghost,
  Gift,
  GraduationCap,
  GripVertical,
  HandCoins,
  Handshake,
  Heart,
  Home,
  Hourglass,
  Image as ImageIcon,
  Info,
  LayoutDashboard,
  Link2,
  ListChecks,
  Lock,
  LogOut,
  type LucideProps,
  Mail,
  Medal,
  MessageCircle,
  Minus,
  Moon,
  Music2,
  NotebookPen,
  Palette,
  Pencil,
  Phone,
  PieChart,
  Pin,
  Play,
  Plus,
  Quote,
  Receipt,
  RefreshCw,
  Repeat,
  Rocket,
  ScrollText,
  Search,
  Send,
  Settings,
  Shield,
  ShieldCheck,
  ShoppingCart,
  Skull,
  SlidersHorizontal,
  Snowflake,
  Sparkles,
  Sprout,
  Square,
  Star,
  Sun,
  Sword,
  Swords,
  Target,
  Trash2,
  TrendingDown,
  TrendingUp,
  TriangleAlert,
  Trophy,
  Turtle,
  Unlock,
  Upload,
  UserMinus,
  Users,
  Volume2,
  Wallet,
  Wand2,
  X,
  Zap,
} from 'lucide-react';

import type { IconName } from '../game/types';

/**
 * One icon system.
 *
 * The app used to mix Lucide line icons (nav, attribute chips) with emoji
 * (Market items, bosses, ranks, statuses, achievement families). Two icon systems
 * side by side is the single loudest "unfinished" signal a UI can send: emoji
 * render differently on every OS, can't inherit the theme's accent colour, and
 * sit on a different optical weight than a 1.8px stroke.
 *
 * Everything visual is a Lucide glyph now. The one deliberate exception is the
 * five mood faces in the Journal — there, the emoji IS the content (a face
 * carries an expression no line icon can), not decoration.
 *
 * `IconName` lives in game/types.ts so the data tables can name an icon without
 * importing a component; this module only supplies the glyph for each name.
 */
export type { IconName };

const ICONS: Record<IconName, React.ComponentType<LucideProps>> = {
  // modules / nav
  dashboard: LayoutDashboard,
  habits: Repeat,
  quests: Swords,
  journal: BookOpen,
  social: Users,
  finances: Wallet,
  market: ShoppingCart,
  achievements: Trophy,
  settings: Settings,
  calendar: Calendar,
  life: PieChart,
  people: Users,
  more: Ellipsis,
  // attributes
  health: Heart,
  friends: Handshake,
  family: Home,
  money: Coins,
  career: Briefcase,
  spirituality: Sparkles,
  development: TrendingUp,
  brightness: Sun,
  // classes (the seven radicals)
  bard: Music2,
  warden: ShieldCheck,
  sovereign: Crown,
  healer: Heart,
  magician: Wand2,
  herald: Sun,
  sentinel: Eye,
  // market items
  potionSmall: FlaskConical,
  potionMedium: FlaskRound,
  potionLarge: Beaker,
  shield: ShieldCheck,
  pardon: ScrollText,
  indulgence: Flame,
  ghost: Ghost,
  feather: Feather,
  focus: Target,
  boost: Zap,
  identity: NotebookPen,
  // weekly bosses — each reads as the neglect it embodies
  bossHealth: Turtle,
  bossFriends: UserMinus,
  bossFamily: Snowflake,
  bossMoney: TrendingDown,
  bossCareer: Anchor,
  bossSpirituality: Aperture,
  bossDevelopment: Cog,
  bossBrightness: CloudFog,
  // rank ladder — a visible ascent from a sliver of moon to a star
  rankSeeker: Moon,
  rankNovice: Sprout,
  rankApprentice: Compass,
  rankAdept: Sword,
  rankJourneyman: Swords,
  rankExpert: Medal,
  rankVeteran: Shield,
  rankMaster: Award,
  rankGrandmaster: Gem,
  rankLegend: Star,
  // achievement families
  famLeveling: Rocket,
  famDiscipline: CheckCheck,
  famStreaks: Flame,
  famQuesting: Swords,
  famDeepWork: Hourglass,
  famReflection: BookOpen,
  famConnections: Handshake,
  famCleanSlate: Receipt,
  famBookkeeping: CreditCard,
  famFortune: Coins,
  famShopping: ShoppingCart,
  famAlchemy: FlaskRound,
  famErrands: Pin,
  famBalance: Contrast,
  famBossHunter: Skull,
  // contact channels
  instagram: Camera,
  whatsapp: MessageCircle,
  telegram: Send,
  phone: Phone,
  email: Mail,
  // cosmetics
  frame: Circle,
  title: Quote,
  banner: ImageIcon,
  // themes
  themeMidnight: Moon,
  themeParchment: ScrollText,
  themeNeon: Zap,
  themeSkeuo: BookMarked,
  // actions / chrome
  gold: Coins,
  check: Check,
  close: X,
  edit: Pencil,
  trash: Trash2,
  plus: Plus,
  minus: Minus,
  starFilled: Star,
  starOutline: Star,
  play: Play,
  stop: Square,
  flag: Flag,
  lock: Lock,
  unlock: Unlock,
  trophy: Trophy,
  grip: GripVertical,
  chronicle: ScrollText,
  wheel: PieChart,
  eye: Eye,
  eyeOff: EyeOff,
  cake: Cake,
  target: Target,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronUp: ChevronUp,
  chevronDown: ChevronDown,
  subscription: RefreshCw,
  chest: Gift,
  flame: Flame,
  sparkles: Sparkles,
  upload: Upload,
  download: Download,
  image: ImageIcon,
  camera: Camera,
  search: Search,
  filter: SlidersHorizontal,
  info: Info,
  warning: TriangleAlert,
  arrowUp: ArrowUp,
  arrowDown: ArrowDown,
  bell: Bell,
  palette: Palette,
  sound: Volume2,
  logout: LogOut,
  link: Link2,
  external: ExternalLink,
  book: BookMarked,
  brain: Brain,
  learn: GraduationCap,
  write: NotebookPen,
  quote: Quote,
  receipt: Receipt,
  card: CreditCard,
  banknote: HandCoins,
  tasks: ListChecks,
};

export function Icon({ name, size = 18, fill, ...props }: { name: IconName; size?: number } & LucideProps) {
  const Cmp = ICONS[name];
  const resolvedFill = fill ?? (name === 'starFilled' ? 'currentColor' : 'none');
  return <Cmp size={size} strokeWidth={1.8} fill={resolvedFill} aria-hidden="true" {...props} />;
}
